### PR TITLE
#162949172 User login

### PR DESCRIPTION
**Pull request by kwanj-k**
#### What does this PR do?

Creates a Login page 

#### Description of Task to be completed?
- [x] Add a user login  form
- [x] Consume the login endpoint

#### How should this be manually tested?

1. Clone the repository
```
git clone https://github.com/andela/ah-the-unsullied-frontend.git
```
2. Cd into the cloned repo
```
cd ah-the-unsullied-frontend
```
3. Checkout to this branch
```
git checkout ft-login-162949172
```
4. Install the dependencies of the project
```
npm install
```
5. Run the app
```
npm start
```
6. Visit the default route `http://localhost:3000/` and click the login button

7. To run tests, run `npm test`

#### What are the relevant pivotal tracker stories?
[#162949172](https://www.pivotaltracker.com/story/show/162949172)

#### Screenshots (if appropriate)
logp

### CODE REVIEW

**Review by younggeeks — APPROVED** [review]
LGTM

**Review by kipropbrian — COMMENTED** [review]
Your logo is not showing, at least from my side.
Your link to the PT story is not in the correct format, check markdown format for linking to stories.

Why are you creating your own algorithm for checking `isEmpty`?

**Comment by kwanj-k** [comment]
> Your logo is not showing, at least from my side.
> Your link to the PT story is not in the correct format, check markdown format for linking to stories.
> 
> Why are you creating your own algorithm for checking `isEmpty`?

@kipropbrian Thanks for the feedback
As for the logo, it is not completely done yet as I concentrated on login at first as per the task description but it's work in progress together with the nav
I will fix the markdown on the PR asap
As for the isEmpty, I needed a method that worked across the board, ie
it could check a string, a variable that has been declared but not defined yet or both null and undefined variables and also check objects.

**Review by sylviawanjiku — APPROVED** [review]

**Review by Allan690 — APPROVED** [review]
LGTM

**Pull request merged**
